name: Build and validate
on:
    pull_request:
        branches: [main]

jobs:
    test:
        name: Test ${{ matrix.go }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 4
            matrix:
                go: [
                    "1.21", 
                    "1.22", 
                    "1.23", 
                    "1.24"
                ]
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Setup Go {{ matrix.go }}
              uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
              with:
                  go-version: ${{ matrix.go }}

            - name: Run tests
              run: |
                go test -v ./...
